# -*- coding: utf-8 -*-
"""AI_Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHNL_cm57Czx8IOqsBzlwx289kJSYkOd
"""

import random

# Dictionary of patterns and responses for a bookstore chatbot
responses = {
    "hi": ["Hello! Welcome to our bookstore.", "Hi there! How can I assist you today?"],
    "order status": ["Let me check the status of your order. Please provide your order number."],
    "book recommendation": ["What genre are you interested in? I can suggest a great book for you."],
    "fiction": ["I recommend 'The Great Gatsby' by F. Scott Fitzgerald."],
    "non-fiction": ["How about 'Sapiens: A Brief History of Humankind' by Yuval Noah Harari?"],
    "thanks": ["You're welcome!", "No problem! If you have any more questions, feel free to ask."],
    "bye": ["Thank you for visiting our bookstore. Have a great day!", "Goodbye! Come back soon."]
}

def chat():
    print("Hello! Welcome to our bookstore. How can I assist you today?")
    while True:
        user_input = input("You: ").lower()
        if user_input == "bye":
            print(random.choice(responses["bye"]))
            break
        elif "hi" in user_input:
            print(random.choice(responses["hi"]))
        elif "order" in user_input:
            print(random.choice(responses["order status"]))
        elif "recommend" in user_input or "suggest" in user_input:
            print(random.choice(responses["book recommendation"]))
        elif "fiction" in user_input:
            print(random.choice(responses["fiction"]))
        elif "non-fiction" in user_input:
            print(random.choice(responses["non-fiction"]))
        elif user_input == "thanks" or user_input == "thank you":
            print(random.choice(responses["thanks"]))
        else:
            print("I'm sorry, I didn't quite catch that. Can you please rephrase or ask another question?")

if __name__ == "__main__":
    chat()